chore(sftp): add sftp methods to sftp feature
cornershop/cornershop-catalog-integrations-api-tools pull request #7
Opened 2021-02-16 20:25 UTC by soroushfall

add sftp methods to sftp PR.
- get_all_files()
- move_files()

2021-02-16 23:58 UTC, soroushfall commented on api_integration_tools/sftp.py
> +        )
change regex when tests have the correct 14 digit timestamp

2021-02-17 23:13 UTC, quentinv72 requested changes

2021-02-17 23:13 UTC, quentinv72 commented on catalog_integrations_api_tools/sftp.py
> +        prepare sftp credentials
```suggestion
        Return SFTP credentials and settings.
```

2021-02-17 23:13 UTC, quentinv72 commented on catalog_integrations_api_tools/sftp.py
> +logger = logging.getLogger(__name__)
I think you should add this as a class variable.

2021-02-17 23:13 UTC, quentinv72 commented on catalog_integrations_api_tools/sftp.py
> +            dict: kwargs for creating sftp connection
```suggestion
            dict: SFTP credentials and settings.
```

2021-02-17 23:13 UTC, quentinv72 commented on catalog_integrations_api_tools/sftp.py
> +        kwargs = self._get_sftp_credentials()
```suggestion
       settings = self._get_sftp_credentials()
```

2021-02-17 23:13 UTC, quentinv72 commented on catalog_integrations_api_tools/sftp.py
> +            rf"{file_prefix}_products_\d+\.csv(\.gz)?", flags=re.I
Why do we need to ignorecase here?

2021-02-17 23:13 UTC, quentinv72 commented on catalog_integrations_api_tools/sftp.py
> +                for filename in sftp.listdir():
```suggestion
            for filename in sftp.listdir(remote_directory):
```

2021-02-17 23:13 UTC, quentinv72 commented on catalog_integrations_api_tools/sftp.py
> +                        logger.info(f"File {filename} downloaded successfully.")
I think we should log this at debug.
```suggestion
                        logger.debug(f"{filename} downloaded successfully.")
```

2021-02-17 23:13 UTC, quentinv72 commented on catalog_integrations_api_tools/sftp.py
> +        Move processed files to /data/cornershop/processed directory on SFTP server.
I think we should revert to the previous docs, because we are allowing to move the files to any other processed directory.

2021-02-17 23:13 UTC, quentinv72 commented on catalog_integrations_api_tools/sftp.py
> +        kwargs = self._get_sftp_credentials()
```suggestion
        settings = self._get_sftp_credentials()
```

2021-02-17 23:13 UTC, quentinv72 commented on catalog_integrations_api_tools/sftp.py
> +                    sftp.mkdir(remote_directory)
I am not sure if we should assume all parent directories already exist.
Something to think about...
```suggestion
                    sftp.makedirs(remote_directory)
```

2021-02-17 23:13 UTC, quentinv72 commented on catalog_integrations_api_tools/sftp.py
> +                logger.info(f"Moved {filename} to {remote_directory}")
```suggestion
                logger.debug(f"Moved {filename} to {remote_directory}")
```

2021-02-17 23:16 UTC, quentinv72 commented on catalog_integrations_api_tools/sftp.py
> +            rf"{file_prefix}_products_\d+\.csv(\.gz)?", flags=re.I
Also, shouldn't the regex be 
`rf"{file_prefix}_products_\d{14,14}\.csv(\.gz)?"`  ??

2021-02-17 23:16 UTC, quentinv72 commented on catalog_integrations_api_tools/sftp.py
> +            rf"{file_prefix}_products_\d+\.csv(\.gz)?", flags=re.I
This question also applies to the stock-prices regex

2021-02-18 15:11 UTC, soroushfall commented on catalog_integrations_api_tools/sftp.py
> +logger = logging.getLogger(__name__)
Why should we do that?

2021-02-18 15:15 UTC, soroushfall commented on catalog_integrations_api_tools/sftp.py
> +            rf"{file_prefix}_products_\d+\.csv(\.gz)?", flags=re.I
If we don't ignore case, the integrator might enter the prefix = "Store_Name" and the files actually start with "store_name" prefix

2021-02-18 15:16 UTC, soroushfall commented on catalog_integrations_api_tools/sftp.py
> +            rf"{file_prefix}_products_\d+\.csv(\.gz)?", flags=re.I
The regex should be ...d{14}, but since the filename in the tests have a different format, I changed it. I made a note to change it back once the tests are changed as well.

2021-02-18 15:34 UTC, soroushfall commented on catalog_integrations_api_tools/sftp.py
> +                    sftp.mkdir(remote_directory)
I don't understand the assumption. Do you mean "/data/cornershop" does not exist?

2021-02-18 15:48 UTC, quentinv72 commented on catalog_integrations_api_tools/sftp.py
> +            rf"{file_prefix}_products_\d+\.csv(\.gz)?", flags=re.I
If the integrators enters `Store_name` instead of `store_name` then that is an error, and it is not our responsibility to catch it and let it pass.
Feel free to change the filenames in the tests then. The regex should have `\d{14}`

2021-02-18 15:52 UTC, quentinv72 commented on catalog_integrations_api_tools/sftp.py
> +                    sftp.mkdir(remote_directory)
If the integrator wants to save move their files to `data/cornershop/files/processed` but the `data/cornershop/files` does not exist yet, it would need to be created before `data/cornershop/files/processed` this directory.
`sftp.mkdir` does not create it whereas `sftp.makedirs` does.

2021-02-18 15:56 UTC, soroushfall commented on catalog_integrations_api_tools/sftp.py
> +                    sftp.mkdir(remote_directory)
I see your point. I'll make that change.

2021-02-18 16:09 UTC, soroushfall commented on catalog_integrations_api_tools/sftp.py
> +            rf"{file_prefix}_products_\d+\.csv(\.gz)?", flags=re.I
ok, will make that change.

2021-02-18 17:34 UTC, soroushfall commented on catalog_integrations_api_tools/sftp.py
> +logger = logging.getLogger(__name__)
done

2021-02-18 21:31 UTC, quentinv72 requested changes

2021-02-18 21:31 UTC, quentinv72 commented on catalog_integrations_api_tools/sftp.py
> +                if sftp.isdir(remote_directory) is False:
```suggestion
                if not sftp.isdir(remote_directory):
```

2021-02-18 21:31 UTC, quentinv72 commented on catalog_integrations_api_tools/sftp.py
> +        )
You don't actually need to compile the regular expressions.
```suggestion
        products_pattern_compiled = f"{file_prefix}_products_" + r"\d{14}\.csv(\.gz)?"
        stockprices_pattern_compiled = f"{file_prefix}_stock-prices_" + r"\d{14}\.csv(\.gz)?"
```

2021-02-19 16:30 UTC, quentinv72 approved these changes

2021-02-19 16:43 UTC, merged